"""add ppassword

Revision ID: 102787da8ab8
Revises: 16348926c9e5
Create Date: 2018-04-14 16:08:45.979774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102787da8ab8'
down_revision = '16348926c9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
