"""add email

Revision ID: 16348926c9e5
Revises: 36dabf4f4071
Create Date: 2018-04-14 01:03:58.854883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16348926c9e5'
down_revision = '36dabf4f4071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
