"""add class Post

Revision ID: 7be1dfa95629
Revises: 8a22d4762431
Create Date: 2018-04-15 19:56:26.941756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be1dfa95629'
down_revision = '8a22d4762431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=225), nullable=False),
    sa.Column('category', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id', 'post')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
