"""verify password

Revision ID: fc32b10684a8
Revises: e3c19a805aa6
Create Date: 2018-04-14 16:46:40.444059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc32b10684a8'
down_revision = 'e3c19a805aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
